// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF0h-BbwplG9rFzxBToiW-XY4TZwB6C4c',
    appId: '1:160807651506:web:4f5a890633e1983d9e61ab',
    messagingSenderId: '160807651506',
    projectId: 'device-connect-pro',
    authDomain: 'device-connect-pro.firebaseapp.com',
    storageBucket: 'device-connect-pro.appspot.com',
    measurementId: 'G-T977J7YCFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-uYV_iWnJAM8Hv64pL7i1iouj9eiwwLI',
    appId: '1:160807651506:android:6bd3177bc18aa79c9e61ab',
    messagingSenderId: '160807651506',
    projectId: 'device-connect-pro',
    storageBucket: 'device-connect-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwWWQ2BBR8Q3dYeWzq60ea9f3IC1sho5s',
    appId: '1:160807651506:ios:7c197dc424f4517d9e61ab',
    messagingSenderId: '160807651506',
    projectId: 'device-connect-pro',
    storageBucket: 'device-connect-pro.appspot.com',
    iosBundleId: 'com.example.leadconnectpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwWWQ2BBR8Q3dYeWzq60ea9f3IC1sho5s',
    appId: '1:160807651506:ios:8905c9e39b0c20479e61ab',
    messagingSenderId: '160807651506',
    projectId: 'device-connect-pro',
    storageBucket: 'device-connect-pro.appspot.com',
    iosBundleId: 'com.example.leadconnectpro.RunnerTests',
  );
}
